### ISSUE TITLE
Doesn't work in FossaMail 25.1.4

### ISSUE THREAD

**Issue by vanowm** [erikvold/restartless-restart-ffext#12]
FossaMail is a faster version of Thunderbird (http://www.fossamail.org/) 

RestartlessRestart installs with no issues, however doesn't add anything in menu, no toolbar button and hotkeys don't work.

No errors:
```
LOG addons.xpi: Starting install of file:///D:/restartless_restart-9-sm+fx+tb+fn.xpi
 ----------
ACR (ERROR) 0:22:46.91: TypeError: addonReportUpdateListeners[i] is not a function
 ----------
LOG addons.xpi: Addon restartless.restart@erikvold.com will be installed as a packed xpi
 ----------
LOG addons.xpi: Loading bootstrap scope from E:\Email_v3\FossaMail\extensions\restartless.restart@erikvold.com.xpi
 ----------
LOG addons.xpi: Calling bootstrap method install on restartless.restart@erikvold.com version 9
 ----------
LOG addons.xpi: Install of file:///D:/restartless_restart-9-sm+fx+tb+fn.xpi completed.
 ----------
LOG addons.xpi: Calling bootstrap method startup on restartless.restart@erikvold.com version 9
```

Would be nice if support for FossaMail was added in the future version.

Thanks.
